
// generated by /home/matt/dev/smaghetti/scripts/createLevelsArchive.js
export const TOTAL_COUNT_MAP: Record<string, number> = {"get_all_published_levels":1190,"get_published_levels_that_have_special_coins":663,"traditional":134,"classic":153,"adventure":210,"kaizo":33,"experimental":62,"difficult":135,"easy":142,"troll":20,"puzzle":39,"speed run":29,"casual":152,"tutorial":22};
