
// generated by /home/matt/dev/smaghetti/scripts/createLevelsArchive.js
export const TOTAL_COUNT_MAP: Record<string, number> = {"get_all_published_levels":1697,"get_published_levels_that_have_special_coins":893,"traditional":158,"classic":213,"adventure":253,"kaizo":89,"experimental":89,"difficult":199,"easy":159,"troll":26,"puzzle":46,"speed run":43,"casual":200,"tutorial":27};
