
// generated by /home/matt/dev/smaghetti/scripts/createLevelsArchive.js
export const TOTAL_COUNT_MAP: Record<string, number> = {"get_all_published_levels":1765,"get_published_levels_that_have_special_coins":927,"traditional":161,"classic":222,"adventure":253,"kaizo":89,"experimental":91,"difficult":201,"easy":161,"troll":26,"puzzle":47,"speed run":44,"casual":209,"tutorial":28};
