import { StaticResource } from './types';

// generated by png2res
const BackgroundHillsStripedSmall: StaticResource = {
	palettes: [
		[
			31744,
			32767,
			0,
			26019,
			31371,
			32622,
			32726,
			5524,
			11833,
			17085,
			8800,
			10952,
			15180,
			18352,
			8767,
			22515,
		],
		[
			31744,
			0,
			32767,
			24035,
			31400,
			5278,
			607,
			9055,
			8973,
			0,
			0,
			0,
			25535,
			0,
			0,
			0,
		],
	],
	tiles: [
		[
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			616,
			617,
			618,
			619,
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			620,
			584,
			578,
			621,
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			586,
			584,
			538,
			539,
			618,
			619,
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
				palette: 1,
			},
			586,
			584,
			542,
			584,
			578,
			621,
		],
		[616, 617, 540, 541, 590, 584, 589, 587],
		[620, 584, 578, 543, 590, 584, 589, 587],
	],
	romOffset: 1455976,
};

export { BackgroundHillsStripedSmall };
