import { StaticResource } from './types';

// generated by png2res
const BackgroundHillsStripedMedium: StaticResource = {
	palettes: [
		[
			31,
			0,
			32767,
			24035,
			31400,
			5278,
			607,
			9055,
			8973,
			0,
			0,
			0,
			25535,
			0,
			0,
			0,
		],
		[
			31,
			32767,
			0,
			26019,
			31371,
			32622,
			32726,
			5524,
			11833,
			17085,
			8800,
			10952,
			15180,
			18352,
			8767,
			22515,
		],
	],
	tiles: [
		[
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1455976,
				tileIndex: 616,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 617,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 618,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 619,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1455976,
				tileIndex: 620,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 578,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 621,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
			{
				romOffset: 1253344,
				tileIndex: 255,
			},
		],
		[
			{
				romOffset: 1455976,
				tileIndex: 616,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 617,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 540,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 541,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 587,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 616,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 617,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 618,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 619,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1455976,
				tileIndex: 620,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 578,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 543,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 587,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 620,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 578,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 621,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1455976,
				tileIndex: 586,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 538,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 539,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 576,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 577,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 590,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 587,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1455976,
				tileIndex: 586,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 542,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 578,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 579,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 590,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 587,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1455976,
				tileIndex: 586,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 590,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 591,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 590,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 587,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1455976,
				tileIndex: 586,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 590,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 591,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 590,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 584,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 589,
				palette: 1,
			},
			{
				romOffset: 1455976,
				tileIndex: 587,
				palette: 1,
			},
		],
	],
};

export { BackgroundHillsStripedMedium };
