import { StaticResource } from './types';

// generated by png2res
const BonusRoomBackground: StaticResource = {
	palettes: [
		[
			32662,
			32767,
			16912,
			20083,
			15150,
			19346,
			26553,
			15994,
			21245,
			30525,
			5819,
			15165,
			22461,
			30440,
			31600,
			31703,
		],
	],
	tiles: [
		[
			868,
			869,
			{
				tileIndex: 842,
				flip: 'h',
			},
			872,
			873,
			{
				tileIndex: 845,
				flip: 'h',
			},
			870,
			871,
		],
		[
			876,
			877,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				tileIndex: 835,
				flip: 'h',
			},
			{
				tileIndex: 834,
				flip: 'h',
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			878,
			879,
		],
		[
			{
				tileIndex: 859,
				flip: 'h',
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			846,
			847,
			864,
			865,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				tileIndex: 838,
				flip: 'h',
			},
		],
		[874, 875, 862, 863, 880, 881, 866, 867],
		[844, 845, 860, 840, 841, 861, 842, 843],
		[
			838,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			839,
			856,
			857,
			858,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			859,
		],
		[
			832,
			833,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			834,
			835,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			836,
			837,
		],
		[848, 849, 850, 851, 852, 853, 854, 855],
	],
	romOffset: 1584308,
};

export { BonusRoomBackground };
