import { StaticResource } from './types';

// generated by png2res
const GhostHouseBackground: StaticResource = {
	palettes: [
		[
			32763,
			32767,
			6342,
			32767,
			19648,
			27108,
			28328,
			21134,
			15918,
			9710,
			138,
			4365,
			8560,
			4392,
			4458,
			9710,
		],
		[
			32763,
			9577,
			0,
			11691,
			15886,
			165,
			297,
			397,
			462,
			562,
			10,
			18,
			19,
			4392,
			4458,
			9710,
		],
	],
	tiles: [
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 15,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 31,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 67,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 66,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 66,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
			{
				romOffset: 1898844,
				tileIndex: 27,
			},
			{
				romOffset: 1898844,
				tileIndex: 28,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 47,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 83,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 82,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 82,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 63,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 60,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 59,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 110,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 7,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 8,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 9,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 10,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 7,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 8,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 9,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 10,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 126,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 5,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 6,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 25,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 26,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 23,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 24,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 25,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 26,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 21,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 22,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 41,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 42,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 39,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 40,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 41,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 42,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 37,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 38,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 57,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 58,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 55,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 56,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 57,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 58,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 111,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 53,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 54,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 73,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 74,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 71,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 72,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 73,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 74,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 127,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 69,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 70,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 89,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 90,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 87,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 56,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 89,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 90,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 85,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 86,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 105,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 106,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 103,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 72,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 105,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 106,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 119,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 120,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 121,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 122,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 119,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 120,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 121,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 122,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 110,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 101,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 102,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 126,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 79,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 117,
				palette: 1,
			},
			{
				romOffset: 1898844,
				tileIndex: 118,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 13,
			},
			{
				romOffset: 1898844,
				tileIndex: 14,
			},
			{
				romOffset: 1898844,
				tileIndex: 15,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
			{
				romOffset: 1898844,
				tileIndex: 11,
			},
			{
				romOffset: 1898844,
				tileIndex: 12,
			},
		],
		[
			{
				romOffset: 1898844,
				tileIndex: 29,
			},
			{
				romOffset: 1898844,
				tileIndex: 30,
			},
			{
				romOffset: 1898844,
				tileIndex: 47,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 83,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 82,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 82,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
			{
				romOffset: 1898844,
				tileIndex: 43,
			},
			{
				romOffset: 1898844,
				tileIndex: 44,
			},
		],
	],
};

export { GhostHouseBackground };
