import { StaticResource } from './types';

// generated by png2res
const GrassChuteDownLeft: StaticResource = {
	palettes: [
		[
			31744,
			32767,
			0,
			557,
			4721,
			9973,
			14201,
			26147,
			31534,
			32726,
			4402,
			6550,
			9787,
			11934,
			0,
			0,
		],
		[
			31744,
			0,
			32767,
			24035,
			31400,
			5278,
			607,
			9055,
			8973,
			0,
			0,
			0,
			25535,
			0,
			0,
			0,
		],
	],
	tiles: [
		[
			{
				romOffset: 1472116,
				tileIndex: 846,
			},
			{
				romOffset: 1472116,
				tileIndex: 847,
			},
			{
				romOffset: 1472116,
				tileIndex: 846,
			},
			{
				romOffset: 1472116,
				tileIndex: 847,
			},
			{
				romOffset: 1472116,
				tileIndex: 846,
			},
			{
				romOffset: 1472116,
				tileIndex: 847,
			},
			{
				romOffset: 1472116,
				tileIndex: 846,
			},
			{
				romOffset: 1472116,
				tileIndex: 837,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 836,
			},
			{
				romOffset: 1472116,
				tileIndex: 847,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 304,
			},
			{
				romOffset: 1584308,
				tileIndex: 305,
			},
			{
				romOffset: 1584308,
				tileIndex: 304,
			},
			{
				romOffset: 1584308,
				tileIndex: 305,
			},
			{
				romOffset: 1584308,
				tileIndex: 304,
			},
			{
				romOffset: 1584308,
				tileIndex: 305,
			},
			{
				romOffset: 1584308,
				tileIndex: 304,
			},
			{
				romOffset: 1472116,
				tileIndex: 822,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 820,
			},
			{
				romOffset: 1584308,
				tileIndex: 305,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1472116,
				tileIndex: 788,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 786,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1472116,
				tileIndex: 789,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 787,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1472116,
				tileIndex: 788,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 786,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1472116,
				tileIndex: 789,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 787,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 275,
			},
			{
				romOffset: 1472116,
				tileIndex: 779,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 786,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 275,
			},
			{
				romOffset: 1472116,
				tileIndex: 778,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 787,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 275,
			},
			{
				romOffset: 1472116,
				tileIndex: 779,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 769,
			},
			{
				romOffset: 1584308,
				tileIndex: 258,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 275,
			},
			{
				romOffset: 1472116,
				tileIndex: 778,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 768,
			},
			{
				romOffset: 1584308,
				tileIndex: 258,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 275,
			},
			{
				romOffset: 1472116,
				tileIndex: 779,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 769,
			},
			{
				romOffset: 1584308,
				tileIndex: 258,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				romOffset: 1584308,
				tileIndex: 256,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1472116,
				tileIndex: 778,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1472116,
				tileIndex: 768,
			},
			{
				romOffset: 1584308,
				tileIndex: 258,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
		],
		[
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 258,
			},
			{
				romOffset: 1584308,
				tileIndex: 257,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 272,
			},
			{
				romOffset: 1584308,
				tileIndex: 273,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
			{
				tileIndex: 255,
				palette: 1,
			},
		],
	],
	romOffset: 1253344,
};

export { GrassChuteDownLeft };
