import { StaticResource } from './types';

// generated by png2res
const GreenMountainsBackground: StaticResource = {
	palettes: [
		[
			32662,
			32767,
			5510,
			9899,
			12013,
			14127,
			16241,
			10987,
			15217,
			4454,
			21394,
			23476,
			512,
			3620,
			5734,
			8873,
		],
		[
			32662,
			32432,
			5510,
			9899,
			12013,
			14127,
			16241,
			10987,
			15217,
			4454,
			21394,
			23476,
			512,
			3620,
			5734,
			8873,
		],
		[
			32662,
			32432,
			352,
			19281,
			20337,
			21394,
			23476,
			10987,
			4430,
			4453,
			5510,
			4464,
			512,
			3620,
			5734,
			8873,
		],
		[
			32662,
			32767,
			352,
			19281,
			20337,
			21394,
			23476,
			10987,
			4430,
			4453,
			5510,
			4464,
			512,
			3620,
			5734,
			8873,
		],
	],
	tiles: [
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 448,
				palette: 1,
			},
			{
				tileIndex: 449,
				palette: 1,
			},
			{
				tileIndex: 450,
				palette: 1,
			},
			{
				tileIndex: 451,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			452,
			453,
			{
				tileIndex: 459,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			455,
			456,
			{
				tileIndex: 459,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			472,
			465,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			454,
			456,
			{
				tileIndex: 459,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 448,
				palette: 2,
			},
			{
				tileIndex: 449,
				palette: 2,
			},
			{
				tileIndex: 450,
				palette: 2,
			},
			{
				tileIndex: 451,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			471,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			455,
			469,
			456,
			{
				tileIndex: 459,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 2,
			},
			{
				tileIndex: 458,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 452,
				palette: 3,
			},
			{
				tileIndex: 453,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			471,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			466,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			454,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			456,
			460,
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 455,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			472,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			455,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			468,
			456,
			461,
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 454,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			464,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			454,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			456,
			461,
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 455,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			464,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			465,
			455,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			456,
			461,
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 454,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			465,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			454,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			467,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			456,
			461,
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 455,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			471,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			470,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			455,
			469,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			456,
			461,
			{
				romOffset: 1486172,
				tileIndex: 506,
			},
			{
				tileIndex: 454,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 457,
				palette: 1,
			},
			458,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			464,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			466,
			{
				romOffset: 1253344,
				tileIndex: 262,
			},
			454,
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
			},
			467,
			456,
			461,
			{
				tileIndex: 455,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				romOffset: 1486172,
				tileIndex: 507,
				palette: 3,
			},
			{
				tileIndex: 456,
				palette: 3,
			},
			{
				tileIndex: 459,
				palette: 2,
			},
		],
		[
			473,
			474,
			475,
			476,
			473,
			474,
			475,
			476,
			473,
			474,
			475,
			476,
			473,
			474,
			475,
			476,
			473,
			474,
			475,
			476,
			477,
			478,
			480,
			481,
			477,
			478,
			{
				tileIndex: 475,
				palette: 3,
			},
			{
				tileIndex: 481,
				palette: 3,
			},
			{
				tileIndex: 477,
				palette: 3,
			},
			{
				tileIndex: 478,
				palette: 3,
			},
			{
				tileIndex: 480,
				palette: 3,
			},
			{
				tileIndex: 481,
				palette: 3,
			},
		],
		[
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
			486,
			487,
			488,
			489,
		],
		[
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
			{
				tileIndex: 490,
				palette: 3,
			},
			{
				tileIndex: 491,
				palette: 3,
			},
			{
				tileIndex: 492,
				palette: 3,
			},
			{
				tileIndex: 493,
				palette: 3,
			},
		],
		[
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
			{
				tileIndex: 494,
				palette: 3,
			},
			{
				tileIndex: 495,
				palette: 3,
			},
		],
		[
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
			{
				tileIndex: 496,
				palette: 3,
			},
			{
				tileIndex: 497,
				palette: 3,
			},
		],
		[
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
			462,
			463,
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
		],
	],
	romOffset: 1599368,
};

export { GreenMountainsBackground };
