import { StaticResource } from './types';

// generated by png2res
const KoopaWing: StaticResource = {
	palettes: [
		[
			31744,
			32767,
			6342,
			12690,
			5686,
			10908,
			500,
			666,
			895,
			17151,
			19026,
			25368,
			30653,
			32763,
			32722,
			29484,
		],
	],
	tiles: [[967], [983]],
	romOffset: 1516784,
};

export { KoopaWing };
