import { StaticResource } from './types';

// generated by png2res
const MetalBrickBackground: StaticResource = {
	palettes: [
		[
			32662,
			32767,
			8456,
			5285,
			6342,
			8456,
			9513,
			5288,
			6345,
			8458,
			9515,
			5290,
			6347,
			8460,
			9517,
			3171,
		],
	],
	tiles: [
		[582, 583, 584, 585],
		[598, 599, 600, 601],
		[584, 585, 582, 583],
		[600, 601, 598, 599],
	],
	romOffset: 1584308,
};

export { MetalBrickBackground };
