import { StaticResource } from './types';

// generated by png2res
const PlainsBackground: StaticResource = {
	palettes: [
		[
			32662,
			6687,
			19026,
			30413,
			31536,
			31634,
			32725,
			16110,
			18224,
			21363,
			32432,
			32465,
			32497,
			32530,
			32563,
			32596,
		],
		[
			32662,
			6687,
			19026,
			30413,
			31536,
			31634,
			32725,
			16110,
			18224,
			21363,
			24502,
			32465,
			32497,
			32530,
			32563,
			32596,
		],
		[
			32662,
			9903,
			19026,
			13949,
			17118,
			19262,
			22431,
			3560,
			5708,
			137,
			3275,
			32596,
			27309,
			28366,
			29423,
			30480,
		],
	],
	tiles: [
		[
			{
				romOffset: 1584308,
				tileIndex: 793,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
			},
			{
				romOffset: 1584308,
				tileIndex: 794,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 793,
				flip: 'h',
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 809,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
			},
			{
				romOffset: 1584308,
				tileIndex: 810,
				flip: 'h',
			},
			{
				romOffset: 1584308,
				tileIndex: 809,
				flip: 'h',
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 781,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 782,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 781,
				flip: 'h',
				palette: 1,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 777,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 777,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 778,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 779,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 780,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 779,
				flip: 'h',
				palette: 1,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 795,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 796,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 795,
				flip: 'h',
				palette: 1,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 797,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 798,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 798,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 797,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 797,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 798,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 768,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 769,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 769,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 769,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 769,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 770,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 797,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 798,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 798,
				flip: 'h',
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 797,
				flip: 'h',
				palette: 1,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 784,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 786,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 784,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 772,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 774,
				palette: 2,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 784,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 788,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 784,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 788,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 784,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 503,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 788,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 815,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 816,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 817,
				palette: 2,
			},
			{
				romOffset: 1486172,
				tileIndex: 511,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 772,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 773,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 774,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 791,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 818,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 819,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 822,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 823,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 824,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 819,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 788,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 792,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 826,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 827,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 824,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 825,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 788,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 792,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 823,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 788,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 792,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 262,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 790,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 804,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 124,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 124,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 124,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 124,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 124,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 806,
				palette: 1,
			},
			{
				romOffset: 1584308,
				tileIndex: 807,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 124,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 806,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 803,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 785,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 789,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 783,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 799,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 785,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 789,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 783,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 799,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 785,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 789,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 783,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 799,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 785,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 789,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 783,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 799,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1584308,
				tileIndex: 811,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 812,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 813,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 814,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 811,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 812,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 813,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 814,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 811,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 812,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 813,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 814,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 811,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 812,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 813,
				palette: 2,
			},
			{
				romOffset: 1584308,
				tileIndex: 814,
				palette: 2,
			},
		],
	],
};

export { PlainsBackground };
