// file generated by /home/matt/dev/jumpclub/entityPipeline/generate.ts

import { Resource, getImageResourceObject } from './resources';

import Goomba from '!file-loader?name=static/[name]-[hash].[ext]!./Goomba.png';
import Player from '!file-loader?name=static/[name]-[hash].[ext]!./Player.png';

const image_resources = {
	Goomba: {
		src: Goomba,
		loaded: false,
		type: 'image',
		resource: getImageResourceObject(),
	} as Resource,
	Player: {
		src: Player,
		loaded: false,
		type: 'image',
		resource: getImageResourceObject(),
	} as Resource,
};

export { image_resources };
