// file generated by /home/matt/dev/jumpclub/tilePipeline/generateAnimations.ts

import { Resource, getImageResourceObject } from './resources';

import Conveyor from '!file-loader?name=static/[name]-[hash].[ext]!./Conveyor.png';

const tile_animation_image_resources = {
  Conveyor: {
  src: Conveyor,
  loaded: false,
  type: 'image',
  resource: getImageResourceObject()
} as Resource,
};

export { tile_animation_image_resources };
