// file generated by /home/matt/dev/jumpclub/entityPipeline/generate.ts

import { EntityType } from '../entities/entityMap_generated';
import { Resource } from './resources';

import RedKoopaTroopa from './RedKoopaTroopa.png';
import Player from './Player.png';
import CardSlotMachine from './CardSlotMachine.png';

const image_resources: Record<EntityType, Resource> = {
	RedKoopaTroopa: {
		url: RedKoopaTroopa,
		type: 'image',
	},
	GreenKoopaTroopa: {
		type: 'extracted',
		url: '',
		romOffset: 0x2282e4,
		tiles: [
			[322, 323],
			[354, 355],
			[386, 387],
			[418, 419],
		],
	},
	Goomba: {
		type: 'extracted',
		url: '',
		romOffset: 0x134104,
		tiles: [
			[394, 395],
			[426, 427],
		],
	},
	Spiny: {
		type: 'extracted',
		url: '',
		romOffset: 0x2282e4,
		tiles: [
			[394, 395],
			[426, 427],
		],
	},
	Player: {
		url: Player,
		type: 'image',
	},
	CardSlotMachine: {
		type: 'extracted',
		tiles: [
			[
				{ romOffset: 0x1d0b58, tileIndex: 0 },
				{ romOffset: 0x1d0b58, tileIndex: 1 },
				{ romOffset: 0x1d0b58, tileIndex: 1 },
				{ romOffset: 0x1d0b58, tileIndex: 0, flip: 'h' },
			],
			[
				{ romOffset: 0x1d0b58, tileIndex: 3 },
				{ romOffset: 0x24b5b8, tileIndex: 10 },
				{ romOffset: 0x24b5b8, tileIndex: 11 },
				{ romOffset: 0x1d0b58, tileIndex: 3, flip: 'h' },
			],
			[
				{ romOffset: 0x1d0b58, tileIndex: 3 },
				{ romOffset: 0x24b5b8, tileIndex: 26 },
				{ romOffset: 0x24b5b8, tileIndex: 27 },
				{ romOffset: 0x1d0b58, tileIndex: 3, flip: 'h' },
			],
			[
				{ romOffset: 0x1d0b58, tileIndex: 0, flip: 'v' },
				{ romOffset: 0x1d0b58, tileIndex: 1, flip: 'v' },
				{ romOffset: 0x1d0b58, tileIndex: 1, flip: 'v' },
				{ romOffset: 0x1d0b58, tileIndex: 0, flip: 'hv' },
			],
		],
		url: '',
	},
};

export { image_resources };
