import { StaticResource } from './types';

// generated by png2res
const StoneFloorUpperRight: StaticResource = {
	palettes: [
		[
			32662,
			32767,
			0,
			25101,
			29297,
			31509,
			32699,
			11445,
			17819,
			22078,
			13805,
			18033,
			23318,
			27546,
			27327,
			31583,
		],
	],
	tiles: [
		[89, 20],
		[119, 92],
	],
	romOffset: 1501760,
};

export { StoneFloorUpperRight };
