import { StaticResource } from './types';

// generated by png2res
const TallHillsBackground: StaticResource = {
	palettes: [
		[
			32662,
			31510,
			32567,
			12915,
			13972,
			15062,
			19257,
			20314,
			24477,
			31477,
			14010,
			16124,
			18237,
			19326,
			22462,
			23519,
		],
		[
			32662,
			31510,
			379,
			31544,
			30420,
			379,
			379,
			379,
			379,
			32432,
			32465,
			32499,
			32533,
			32567,
			8654,
			8654,
		],
		[
			32662,
			31510,
			379,
			31544,
			30420,
			379,
			379,
			379,
			379,
			31477,
			32465,
			32499,
			32533,
			32567,
			8654,
			8654,
		],
	],
	tiles: [
		[
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
			{
				tileIndex: 592,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
			{
				tileIndex: 599,
				palette: 2,
			},
		],
		[
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
			{
				tileIndex: 600,
				palette: 2,
			},
		],
		[
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
			{
				tileIndex: 601,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				tileIndex: 593,
				palette: 2,
			},
			{
				tileIndex: 594,
				palette: 2,
			},
			{
				tileIndex: 595,
				palette: 2,
			},
			{
				tileIndex: 596,
				palette: 2,
			},
			{
				tileIndex: 597,
				palette: 2,
			},
			{
				tileIndex: 598,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				tileIndex: 608,
				palette: 2,
			},
			{
				tileIndex: 609,
				palette: 2,
			},
			{
				tileIndex: 610,
				palette: 2,
			},
			{
				tileIndex: 611,
				palette: 2,
			},
			{
				tileIndex: 612,
				palette: 2,
			},
			{
				tileIndex: 613,
				palette: 2,
			},
			{
				tileIndex: 614,
				palette: 2,
			},
			{
				tileIndex: 615,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				tileIndex: 593,
				palette: 2,
			},
			{
				tileIndex: 594,
				palette: 2,
			},
			{
				tileIndex: 595,
				palette: 2,
			},
			{
				tileIndex: 596,
				palette: 2,
			},
			{
				tileIndex: 597,
				palette: 2,
			},
			{
				tileIndex: 598,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				tileIndex: 624,
				palette: 2,
			},
			{
				tileIndex: 625,
				palette: 2,
			},
			{
				tileIndex: 626,
				palette: 2,
			},
			{
				tileIndex: 627,
				palette: 2,
			},
			{
				tileIndex: 627,
				flip: 'h',
				palette: 2,
			},
			{
				tileIndex: 629,
				palette: 2,
			},
			{
				tileIndex: 630,
				palette: 2,
			},
			{
				tileIndex: 631,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				tileIndex: 608,
				palette: 2,
			},
			{
				tileIndex: 609,
				palette: 2,
			},
			{
				tileIndex: 610,
				palette: 2,
			},
			{
				tileIndex: 611,
				palette: 2,
			},
			{
				tileIndex: 612,
				palette: 2,
			},
			{
				tileIndex: 613,
				palette: 2,
			},
			{
				tileIndex: 614,
				palette: 2,
			},
			{
				tileIndex: 615,
				palette: 2,
			},
			{
				tileIndex: 633,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				tileIndex: 591,
				palette: 2,
			},
			{
				tileIndex: 591,
				flip: 'h',
				palette: 2,
			},
			622,
			{
				tileIndex: 623,
				palette: 2,
			},
			{
				tileIndex: 628,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				tileIndex: 624,
				palette: 2,
			},
			{
				tileIndex: 625,
				palette: 2,
			},
			{
				tileIndex: 626,
				palette: 2,
			},
			{
				tileIndex: 627,
				palette: 2,
			},
			{
				tileIndex: 627,
				flip: 'h',
				palette: 2,
			},
			{
				tileIndex: 629,
				palette: 2,
			},
			{
				tileIndex: 630,
				palette: 2,
			},
			{
				tileIndex: 631,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			622,
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				tileIndex: 575,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				tileIndex: 633,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				tileIndex: 591,
				palette: 2,
			},
			{
				tileIndex: 591,
				flip: 'h',
				palette: 2,
			},
			622,
			{
				tileIndex: 623,
				palette: 2,
			},
			{
				tileIndex: 628,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			622,
			{
				romOffset: 1486172,
				tileIndex: 503,
			},
			{
				tileIndex: 575,
				palette: 2,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			602,
			553,
			554,
			605,
			606,
			607,
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			602,
			553,
			554,
			579,
			580,
			581,
			{
				romOffset: 1253344,
				tileIndex: 78,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			616,
			617,
			530,
			531,
			532,
			533,
			618,
			619,
			616,
			617,
			530,
			531,
			532,
			533,
			584,
			585,
		],
		[
			605,
			606,
			607,
			{
				romOffset: 1253344,
				tileIndex: 44,
			},
			620,
			545,
			546,
			547,
			548,
			549,
			550,
			621,
			620,
			545,
			546,
			547,
			548,
			549,
			550,
			587,
		],
		[
			532,
			533,
			618,
			619,
			636,
			561,
			562,
			563,
			564,
			565,
			566,
			637,
			636,
			561,
			562,
			563,
			564,
			565,
			566,
			589,
		],
		[
			548,
			549,
			550,
			621,
			520,
			521,
			522,
			519,
			512,
			525,
			526,
			527,
			520,
			521,
			522,
			519,
			512,
			525,
			526,
			527,
		],
		[
			564,
			565,
			566,
			637,
			536,
			537,
			538,
			539,
			540,
			541,
			542,
			543,
			536,
			537,
			538,
			539,
			540,
			541,
			542,
			543,
		],
		[
			512,
			525,
			526,
			527,
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
		],
		[
			540,
			541,
			542,
			543,
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
		],
		[
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			520,
			521,
			522,
			519,
			512,
			513,
			514,
			515,
			516,
			517,
			518,
			519,
			512,
			525,
			526,
			527,
		],
		[
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			536,
			537,
			538,
			539,
			528,
			529,
			530,
			531,
			532,
			533,
			534,
			535,
			540,
			541,
			542,
			543,
		],
		[
			512,
			525,
			526,
			527,
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			544,
			545,
			546,
			547,
			548,
			549,
			550,
			551,
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
		],
		[
			540,
			541,
			542,
			543,
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			560,
			561,
			562,
			563,
			564,
			565,
			566,
			567,
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
		],
		[
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			520,
			521,
			522,
			519,
			520,
			521,
			522,
			519,
			512,
			525,
			526,
			527,
			512,
			525,
			526,
			527,
		],
		[
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			536,
			537,
			538,
			539,
			536,
			537,
			538,
			539,
			540,
			541,
			542,
			543,
			540,
			541,
			542,
			543,
		],
		[
			512,
			525,
			526,
			527,
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
		],
		[
			540,
			541,
			542,
			543,
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
		],
		[
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			520,
			521,
			522,
			519,
			520,
			521,
			522,
			519,
			512,
			525,
			526,
			527,
			512,
			525,
			526,
			527,
		],
		[
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			536,
			537,
			538,
			539,
			536,
			537,
			538,
			539,
			540,
			541,
			542,
			543,
			540,
			541,
			542,
			543,
		],
		[
			512,
			525,
			526,
			527,
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			{
				tileIndex: 536,
				flip: 'v',
			},
			{
				tileIndex: 537,
				flip: 'v',
			},
			{
				tileIndex: 538,
				flip: 'v',
			},
			{
				tileIndex: 539,
				flip: 'v',
			},
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
		],
		[
			540,
			541,
			542,
			543,
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			{
				tileIndex: 520,
				flip: 'v',
			},
			{
				tileIndex: 521,
				flip: 'v',
			},
			{
				tileIndex: 522,
				flip: 'v',
			},
			{
				tileIndex: 519,
				flip: 'v',
			},
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
		],
		[
			{
				tileIndex: 540,
				flip: 'v',
			},
			{
				tileIndex: 541,
				flip: 'v',
			},
			{
				tileIndex: 542,
				flip: 'v',
			},
			{
				tileIndex: 543,
				flip: 'v',
			},
			520,
			521,
			522,
			519,
			520,
			521,
			522,
			519,
			512,
			525,
			526,
			527,
			512,
			525,
			526,
			527,
		],
		[
			{
				tileIndex: 512,
				flip: 'v',
			},
			{
				tileIndex: 525,
				flip: 'v',
			},
			{
				tileIndex: 526,
				flip: 'v',
			},
			{
				tileIndex: 527,
				flip: 'v',
			},
			536,
			537,
			538,
			539,
			536,
			537,
			538,
			539,
			540,
			541,
			542,
			543,
			540,
			541,
			542,
			543,
		],
	],
	romOffset: 1599368,
};

export { TallHillsBackground };
