import { StaticResource } from './types';

// generated by png2res
const TetrisRoomBackground: StaticResource = {
	palettes: [
		[
			32662,
			30413,
			31536,
			31634,
			32725,
			32763,
			18224,
			21363,
			24502,
			27639,
			31741,
			31319,
			31417,
			31515,
			31613,
			31678,
		],
	],
	tiles: [
		[
			{
				romOffset: 2406440,
				tileIndex: 3,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 5,
			},
			{
				romOffset: 2406440,
				tileIndex: 0,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 2,
			},
			{
				romOffset: 2406440,
				tileIndex: 6,
			},
			{
				romOffset: 2406440,
				tileIndex: 7,
			},
			{
				romOffset: 2406440,
				tileIndex: 7,
			},
			{
				romOffset: 2406440,
				tileIndex: 8,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 35,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 12,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 32,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 34,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 0,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 2,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 6,
			},
			{
				romOffset: 2406440,
				tileIndex: 7,
			},
			{
				romOffset: 2406440,
				tileIndex: 7,
			},
			{
				romOffset: 2406440,
				tileIndex: 7,
			},
			{
				romOffset: 2406440,
				tileIndex: 30,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 38,
			},
			{
				romOffset: 2406440,
				tileIndex: 39,
			},
			{
				romOffset: 2406440,
				tileIndex: 39,
			},
			{
				romOffset: 2406440,
				tileIndex: 39,
			},
			{
				romOffset: 2406440,
				tileIndex: 14,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 27,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 4,
			},
			{
				romOffset: 2406440,
				tileIndex: 5,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 19,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 2406440,
				tileIndex: 21,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 35,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 36,
			},
			{
				romOffset: 2406440,
				tileIndex: 37,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 25,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 1,
			},
			{
				romOffset: 2406440,
				tileIndex: 2,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 16,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 2406440,
				tileIndex: 18,
			},
			{
				romOffset: 2406440,
				tileIndex: 22,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 2406440,
				tileIndex: 24,
			},
		],
		[
			{
				romOffset: 2406440,
				tileIndex: 32,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 33,
			},
			{
				romOffset: 2406440,
				tileIndex: 34,
			},
			{
				romOffset: 2406440,
				tileIndex: 38,
			},
			{
				romOffset: 2406440,
				tileIndex: 39,
			},
			{
				romOffset: 2406440,
				tileIndex: 39,
			},
			{
				romOffset: 2406440,
				tileIndex: 40,
			},
		],
	],
};

export { TetrisRoomBackground };
