import { StaticResource } from './types';

// generated by png2res
const TetrisRoomBackground: StaticResource = {
	palettes: [
		[
			32662,
			30413,
			31536,
			31634,
			32725,
			32763,
			18224,
			21363,
			24502,
			27639,
			31741,
			31319,
			31417,
			31515,
			31613,
			31678,
		],
	],
	tiles: [
		[3, 4, 4, 4, 4, 4, 4, 5, 0, 1, 1, 2, 6, 7, 7, 8],
		[
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			35,
			36,
			36,
			36,
			12,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			32,
			33,
			33,
			34,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			0,
			1,
			1,
			2,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			6,
			7,
			7,
			7,
			30,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			38,
			39,
			39,
			39,
			14,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			27,
			4,
			4,
			4,
			5,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			19,
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			{
				romOffset: 1486172,
				tileIndex: 509,
			},
			21,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			35,
			36,
			36,
			36,
			36,
			36,
			36,
			37,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			25,
			1,
			1,
			1,
			1,
			1,
			1,
			1,
			2,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[
			16,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			18,
			22,
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			{
				romOffset: 1253344,
				tileIndex: 72,
			},
			24,
		],
		[32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 38, 39, 39, 40],
	],
	romOffset: 2406440,
};

export { TetrisRoomBackground };
