import { StaticResource } from './types';

// generated by png2res
const UnderwaterBackground: StaticResource = {
	palettes: [
		[
			32662,
			32767,
			0,
			420,
			4582,
			6698,
			9869,
			6493,
			14815,
			21183,
			5449,
			8587,
			10701,
			12815,
			12016,
			16977,
		],
		[
			32662,
			24896,
			0,
			420,
			4582,
			6698,
			9869,
			6493,
			14815,
			21183,
			5449,
			8587,
			10701,
			12815,
			12016,
			16977,
		],
	],
	tiles: [
		[
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
			{
				tileIndex: 513,
				palette: 1,
			},
			{
				tileIndex: 514,
				palette: 1,
			},
			{
				tileIndex: 515,
				palette: 1,
			},
			{
				tileIndex: 517,
				palette: 1,
			},
			{
				tileIndex: 513,
				palette: 1,
			},
			{
				tileIndex: 514,
				palette: 1,
			},
			{
				tileIndex: 515,
				palette: 1,
			},
			{
				tileIndex: 517,
				palette: 1,
			},
			{
				tileIndex: 513,
				palette: 1,
			},
			{
				tileIndex: 514,
				palette: 1,
			},
			{
				tileIndex: 515,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 528,
				palette: 1,
			},
			{
				tileIndex: 529,
				palette: 1,
			},
			{
				tileIndex: 530,
				palette: 1,
			},
			{
				tileIndex: 532,
				palette: 1,
			},
			{
				tileIndex: 533,
				palette: 1,
			},
			{
				tileIndex: 529,
				palette: 1,
			},
			{
				tileIndex: 530,
				palette: 1,
			},
			{
				tileIndex: 532,
				palette: 1,
			},
			{
				tileIndex: 533,
				palette: 1,
			},
			{
				tileIndex: 529,
				palette: 1,
			},
			{
				tileIndex: 530,
				palette: 1,
			},
			{
				tileIndex: 531,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 544,
				palette: 1,
			},
			545,
			546,
			548,
			549,
			545,
			546,
			548,
			549,
			545,
			546,
			{
				tileIndex: 547,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 560,
				palette: 1,
			},
			561,
			{
				tileIndex: 562,
				palette: 1,
			},
			564,
			565,
			561,
			{
				tileIndex: 562,
				palette: 1,
			},
			564,
			565,
			561,
			{
				tileIndex: 562,
				palette: 1,
			},
			{
				tileIndex: 563,
				palette: 1,
			},
			{
				romOffset: 1253344,
				tileIndex: 44,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 534,
				palette: 1,
			},
			625,
			624,
			625,
			624,
			625,
			624,
			625,
			624,
			625,
			624,
			{
				tileIndex: 535,
				palette: 1,
			},
			{
				tileIndex: 534,
				palette: 1,
			},
		],
		[572, 573, 572, 573, 572, 573, 572, 573, 572, 573, 572, 573, 572],
		[556, 557, 556, 557, 556, 557, 556, 557, 556, 557, 556, 557, 556],
		[572, 573, 572, 573, 572, 573, 572, 573, 572, 573, 572, 573, 572],
	],
	romOffset: 1584308,
};

export { UnderwaterBackground };
