import { StaticResource } from './types';

// generated by png2res
const WinterBackground: StaticResource = {
	palettes: [
		[
			32662,
			32767,
			32733,
			30522,
			31675,
			31607,
			30517,
			19218,
			18129,
			16015,
			28439,
			30585,
			24373,
			23316,
			21211,
			18007,
		],
		[
			32662,
			32432,
			6342,
			30522,
			31513,
			31480,
			32471,
			32438,
			379,
			29496,
			28439,
			29432,
			27318,
			25204,
			23090,
			21009,
		],
		[
			32662,
			32767,
			6342,
			30522,
			31513,
			31480,
			32471,
			32438,
			379,
			29496,
			28439,
			29432,
			27318,
			25204,
			23090,
			21009,
		],
	],
	tiles: [
		[
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
			{
				tileIndex: 144,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
			{
				tileIndex: 153,
				palette: 1,
			},
		],
		[
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
			{
				tileIndex: 162,
				palette: 2,
			},
		],
		[
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
			{
				tileIndex: 171,
				palette: 2,
			},
		],
		[
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
			{
				tileIndex: 180,
				palette: 2,
			},
		],
		[
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
			{
				tileIndex: 191,
				palette: 2,
			},
		],
		[
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
			{
				tileIndex: 203,
				palette: 2,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			129,
			130,
			131,
			132,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			133,
			134,
			135,
			136,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
		],
		[
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
			138,
			139,
			140,
			141,
			142,
			143,
			{
				romOffset: 1253344,
				tileIndex: 254,
			},
		],
		[145, 146, 147, 148, 149, 150, 151, 152],
		[154, 155, 156, 157, 158, 159, 160, 161],
		[163, 164, 165, 166, 167, 168, 169, 170],
		[172, 173, 174, 175, 176, 177, 178, 179],
		[181, 182, 183, 184, 185, 186, 187, 188],
		[192, 193, 194, 195, 196, 197, 198, 199],
		[204, 227, 229, 205, 206, 227, 229, 208],
		[
			204,
			{
				tileIndex: 128,
				flip: 'h',
			},
			128,
			205,
			206,
			{
				tileIndex: 128,
				flip: 'h',
			},
			128,
			{
				tileIndex: 204,
				flip: 'h',
			},
		],
		[
			204,
			{
				tileIndex: 128,
				flip: 'h',
			},
			128,
			207,
			206,
			{
				tileIndex: 128,
				flip: 'h',
			},
			128,
			{
				tileIndex: 204,
				flip: 'h',
			},
		],
		[
			{
				tileIndex: 214,
				palette: 2,
			},
			{
				tileIndex: 214,
				flip: 'h',
				palette: 2,
			},
			{
				tileIndex: 214,
				palette: 2,
			},
			{
				tileIndex: 214,
				flip: 'h',
				palette: 2,
			},
			{
				tileIndex: 214,
				palette: 2,
			},
			{
				tileIndex: 214,
				flip: 'h',
				palette: 2,
			},
			{
				tileIndex: 214,
				palette: 2,
			},
			{
				tileIndex: 214,
				flip: 'h',
				palette: 2,
			},
		],
	],
	romOffset: 1599368,
};

export { WinterBackground };
