// this file was generated by
// /home/matt/dev/jumpclub/entityPipeline/generate.ts

const entityMap = {
	Goomba: {
		width: 16,
		height: 16,
	},
	Player: {
		width: 16,
		height: 16,
	},
	Goal: {
		width: 16,
		height: 16,
	},
	Start: {
		width: 16,
		height: 16,
	},
};

type EntityType = keyof typeof entityMap;

export { entityMap };
export type { EntityType };
