// this file was generated by
// /home/matt/dev/jumpclub/entityPipeline/generate.ts

const entityMap = {
	GreenKoopaTroopa: {
		width: 16,
		height: 32,
	},
	RedKoopaTroopa: {
		width: 16,
		height: 32,
	},
	Goomba: {
		width: 16,
		height: 16,
	},
	Player: {
		width: 16,
		height: 16,
	},
	CardSlotMachine: {
		width: 26,
		height: 26,
	},
};

type EntityType = keyof typeof entityMap;

export { entityMap };
export type { EntityType };
