export const INITIAL_LEVEL_TILE_WIDTH = 120;
export const INITIAL_LEVEL_TILE_HEIGHT = 20;
export const PLAY_WINDOW_TILE_WIDTH = 24;
export const PLAY_WINDOW_TILE_HEIGHT = 14;
export const INITIAL_PLAYER_X_TILE = 2;
export const INITIAL_PLAYER_Y_TILE = INITIAL_LEVEL_TILE_HEIGHT - 3;

export const MAX_LEVEL_TILE_WIDTH = 240;
export const MIN_LEVEL_TILE_WIDTH = PLAY_WINDOW_TILE_WIDTH;

export const MAX_LEVEL_TILE_HEIGHT = 240;
export const MIN_LEVEL_TILE_HEIGHT = PLAY_WINDOW_TILE_HEIGHT;
