// this file was generated by
// /home/matt/dev/jumpclub/tilePipeline/generate.ts

import { ObjectType } from '../entities/entityMap';

type TileHasEntityType = never;
type TileEntityType = never;
type EndCapType = 'start' | 'end' | 'both' | 'none';
type TileGroupType = 'none' | 'x' | 'y' | 'xy' | 'xytopper';
type TopperType = never;
type ToppedType = never;
type HasXEndCapType = never;
type HasYEndCapType = never;

const TILE_SIZE = 16;
const TILE_TYPE_COUNT = 2;

const TILE_TYPE_TO_TILE_ENTITY_TYPE: Record<
	TileHasEntityType,
	TileEntityType
> = {};

const TILE_TYPE_TO_SERIALIZE_ID_MAP: Record<ObjectType, string> = {
	Brick: 'Br',
	IndestructibleBrick: 'In',
	Coin: '$',
	QuestionBlock: '?',
	PSwitch: 'Ps',
	TriangularBlock: 'Tb',
	MusicBlock: 'Mb',
	Muncher: 'Mu',
};

const TILE_SERIALIZED_ID_TO_TYPE_MAP: Record<string, ObjectType> = {
	Br: 'Brick',
	In: 'IndestructibleBrick',
	$: 'Coin',
	'?': 'QuestionBlock',
	Ps: 'PSwitch',
	Tb: 'TriangularBlock',
	Mb: 'MusicBlock',
	Mu: 'Muncher',
};

const TILE_TYPE_TO_GROUP_TYPE_MAP: Record<ObjectType, TileGroupType> = {
	Brick: 'none',
	IndestructibleBrick: 'none',
	Coin: 'none',
	QuestionBlock: 'none',
	PSwitch: 'none',
	TriangularBlock: 'none',
	MusicBlock: 'none',
	Muncher: 'none',
};

const TILE_TOPPER_TO_TOPPED_MAP: Record<TopperType, ObjectType> = {};
const TILE_TOPPED_TO_TOPPER_MAP: Record<ToppedType, ObjectType> = {};

const TILE_TYPE_TO_X_ENDCAPS_MAP: Record<HasXEndCapType, EndCapType> = {};

const TILE_TYPE_TO_Y_ENDCAPS_MAP: Record<HasYEndCapType, EndCapType> = {};

export {
	TILE_SIZE,
	TILE_TYPE_COUNT,
	TILE_TYPE_TO_SERIALIZE_ID_MAP,
	TILE_SERIALIZED_ID_TO_TYPE_MAP,
	TILE_TYPE_TO_GROUP_TYPE_MAP,
	TILE_TOPPER_TO_TOPPED_MAP,
	TILE_TOPPED_TO_TOPPER_MAP,
	TILE_TYPE_TO_X_ENDCAPS_MAP,
	TILE_TYPE_TO_Y_ENDCAPS_MAP,
	TILE_TYPE_TO_TILE_ENTITY_TYPE,
};

export type {
	ObjectType,
	TileHasEntityType,
	TileEntityType,
	EndCapType,
	TileGroupType,
	ToppedType,
	TopperType,
	HasXEndCapType,
	HasYEndCapType,
};
