const rawMusic = `
1:Underground
2:Underwater
3:Fortress
4:BossBattle
5:Airship
6:Hammerbros
7:P-Switch&MushroomHouse
8:Hills
9:Castleroom
A:Clouds/Sky
B:Underground(sameas01)
C:ClassicOverworld
D:ClassicUnderground(nodifferencefromothers)
E:ClassicUnderwater
F:ClassicCastle
10:GhostHouse
11:NoMusic
12:NoMusic
13:Crash(GBAGlitch)
14:GameSelectionScreen
15:GameSelectionScreen
16:MarioBros.ClassicResultscut-off(inotherAdvancegames;lookatTCRF)
17:Crash(GBAGlitch)
18:GameSelectionScreen
19:GameSelectionScreen
1A:Crash
1B:BonusRoom
1C:GameSelectionScreen
1D:GameSelectionScreen
1E:NoMusic
1F:NoMusic
20:GameSelectionScreen
21:GameSelectionScreen
22:Crash
23:BonusRoom
24:GameSelectionScreen
25:GameSelectionScreen
26:Hills(cutsoutafterawhile)
27:Endingre-arranged
28:GameSelectionScreen
29:GameSelectionScreen
2A:MarioBrosClassicStageCompleteSound
2B:ScanCard
2C:GameSelectionScreen
2D:GameSelectionScreen
2E:MarioBrosClassicGameOver"short"
2F:P-Switchloop(MarioWorld)
30:GameSelectionScreen
31:GameSelectionScreen
32:Crash
33:ScanCard
34:GameSelectionScreen
35:GameSelectionScreen
36:Crash
37:MusicBox
38:GameSelectionScreen
39:GameSelectionScreen
3A:LevelClear
3B:ScanCard
3C:GameSelectionScreen
3D:GameSelectionScreen
3E:World5TheSky(LandSegment)
3F:World8DarkWorld
40:GameSelectionScreen
41:GameSelectionScreen
42:Hills
43:ScanCard
44:GameSelectionScreen
45:GameSelectionScreen
46:ScanCard
47:NoMusic
48:GameSelectionScreen
49:GameSelectionScreen
4A:CourseClearwithlifebonus
4B:ScanCard
4C:GameSelectionScreen
4D:GameSelectionScreen
4E:Plains
4F:CourseClearwithlifebonus
50:GameSelectionScreen
51:GameSelectionScreen
52:GameSelectionScreen
53:MarioBros.ClassicResultscut-off
54:GameSelectionScreen
55:GameSelectionScreen
56:MarioBros.ClassicResultscut-off
57:MarioBros.ClassicResultscut-off
58:GameSelectionScreen
59:GameSelectionScreen
5A:Crash
5B:ScanCard
5C:GameSelectionScreen
5D:GameSelectionScreen
5E:NoMusic
5F:Crash
60:GameSelectionScreen
61:GameSelectionScreen
62:GameSelectionScreen
63:ScanCard
64:GameSelectionScreen
65:GameSelectionScreen
66:Hills
67:NoMusic
68:GameSelectionScreen
69:GameSelectionScreen
6A:GameSelectionScreen
6B:ScanCard
6C:GameSelectionScreen
6D:GameSelectionScreen
6E:MarioBrosClassicGameOver"short"
6F:NoMusic
70:MarioBrosClassicGameOver"short"
71:GameSelectionScreen
72:Crash
73:ScanCard
74:GameSelectionScreen
75:GameSelectionScreen
76:Crash
77:NoMusic
78:GameSelectionScreen
79:GameSelectionScreen
7A:CouseClear
7B:ScanCard
7C:GameSelectionScreen
7D:GameSelectionScreen
7E:World5
7F:Crash
80:GameSelectionScreen
81:GameSelectionScreen
82:Hills
83:ScanCard
84:GameSelectionScreen
85:GameSelectionScreen
86:ScanCard
87:Crash
88:GameSelectionScreen
89:GameSelectionScreen
8A:CouseClear
8B:ScanCard
8C:GameSelectionScreen
8D:GameSelectionScreen
8E:Plains
8F:Crash
90:GameSelectionScreen
91:GameSelectionScreen
92:NoMusic
93:NoMusic
94:SMB3TitleScreen
95:GameSelectionScreen
96:GameSelectionScreen
97:NoMusic
98:SMB3TtitleScreen
99:GameSelectionScreen
9A:Crash
9B:SMA4TitleScreen
9C:SMB3TtitleScreen
9D:GameSelectionScreen
9E:GameSelectionScreen
9F:GameSelectionScreen
A0:SMB3TtitleScreen
A1:GameSelectionScreen
A2:Crash
A3:SMB3TtitleScreen
A4:SMB3TtitleScreen
A5:GameSelectionScreen
A6:Hills
A7:WorldSelectionMap
A8:SMB3TtitleScreen
A9:GameSelectionScreen
AA:MarioBrosClassicStageClear
AB:World1GrassLand
AC:SMB3TtitleScreen
AD:GameSelectionScreen
AE:MarioBrosClassicGameOver"short"
AF:World2DesertHill
B0:SMB3TtitleScreen
B1:GameSelectionScreen
B2:Crash
B3:World3SeaSide
B4:SMB3TtitleScreen
B5:GameSelectionScreen
B6:Crash
B7:World4GiantLand
B8:SMB3TtitleScreen
B9:GameSelectionScreen
BA:CouseClear
BB:World5
BC:SMB3TtitleScreen
BD:GameSelectionScreen
BE:World5
BF:World5TheSky(SkySegment)
C0:SMB3TtitleScreen
C1:GameSelectionScreen
C2:Hills
C3:World6WinterWonderland
C4:SMB3TtitleScreen
C5:GameSelectionScreen
C6:ScanCard
C7:World7
C8:SMB3TtitleScreen
C9:GameSelectionScreen
CA:CourseClear
CB:World8
CC:SMB3TtitleScreen
CD:GameSelectionScreen
CE:Plains
CF:World9WarpZona
D0:SMB3TtitleScreen
D1:GameSelectionScreen
D2:NoMusic
D3:Plains
D4:SMB3TtitleScreen
D5:GameSelectionScreen
D6:Plains
D7:Plains
D8:SMB3TtitleScreen
D9:GameSelectionScreen
DA:Crash
DB:Hills
DC:SMB3TtitleScreen
DD:GameSelectionScreen
DE:NoMusic
DF:Underground
E0:SMB3TtitleScreen
E1:GameSelectionScreen
E2:Crash
E3:Underwater
E4:SMB3TtitleScreen
E5:GameSelectionScreen
E6:Hills
E7:Fortress
E8:SMB3TtitleScreen
E9:GameSelectionScreen
EA:MarioBrosClassicStageClear
EB:Airship
EC:SMB3TtitleScreen
ED:GameSelectionScreen
EE:MarioBrosClassicGameOver"short"
EF:BossBattle
F0:SMB3TtitleScreen
F1:GameSelectionScreen
F2:Crash
F3:HammerBros
F4:SMB3TtitleScreen
F5:GameSelectionScreen
F6:Crash
F7:BowserBattle
F8:SMB3TtitleScreen
F9:GameSelectionScreen
FA:CourseClear
FB:P-Switch
FC:SMB3TtitleScreen
FD:GameSelectionScreen
FE:World5
FF:Invincibility`;

const lines = rawMusic.split('\n').map((l) => l.trim());

const musicMap = lines.reduce<Record<string, number>>((building, line) => {
	const split = line.split(':');
	const title = split[1];
	const id = parseInt(split[0], 16);

	if (!building[title]) {
		building[title] = id;
	}

	return building;
}, {});

console.log(JSON.stringify(musicMap, null, 2));

export {};
